apiVersion: v2
name: blackbox-exporter-helm
description: A Helm chart to install Blackbox exporter
version: 1.0.3
appVersion: "11.6.1"

dependencies:
  - name: prometheus-blackbox-exporter 
    version: 11.6.1
    repository: https://prometheus-community.github.io/helm-charts/
  - name: apc-global-overrides
    version: 1.5.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/