proxy: ~
noProxy: ~
proxyCIDRs:
  - 1.1.1.1/32
  - 8.8.8.8/32
cluster:
  appsDomain: apps.cluster.example.com
  apiURL: https://api.cluster.example.com:6443
prometheus-blackbox-exporter:
  ### Proxy Setup
  extraEnvFrom: []