apiVersion: v2
name: vault-helm
description: A Helm chart for bootstrapping the Vault in APC
type: application
version: 1.0.0
appVersion: "1.14.8"
dependencies:
  - name: vault
    version: 0.30.0
    repository: https://helm.releases.hashicorp.com
