apiVersion: v2
name: acs-config
description: A Helm chart for Red Hat Advanced Cluster Security SecuredCluster instance and Central ACS components
type: application
version: 1.0.0

dependencies:
  - name: apc-global-overrides
    version: 1.5.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/