apiVersion: v2
name: crossplane-helm
description: A Helm chart to install Crossplane
type: application
version: 2.1.0
appVersion: "2.1.3"
dependencies:
  - name: crossplane
    version: 2.1.3
    repository: https://charts.crossplane.io/stable
  - name: apc-global-overrides
    version: 1.5.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
