apiVersion: v2
name: crossplane-helm
description: A Helm chart to install Crossplane
type: application
version: 1.6.0
appVersion: "1.20.4"
dependencies:
  - name: crossplane
    version: 1.20.4
    repository: https://charts.crossplane.io/stable
  - name: apc-global-overrides
    version: 1.5.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
