# # shouldn't be ready, but autocreate didn't work
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ck-kafka-kafka-backup-pvc
#   namespace: ck-kafka
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: ocs-storagecluster-ceph-rbd
#   volumeMode: Filesystem
