apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apc-kafka-admin-with-username
  namespace: ck-kafka
spec:
  secretStoreRef:
    name: local-k8s-store
    kind: SecretStore
  refreshInterval: "0"
  #refreshPolicy it is not supported for external-secrets v 0.11
  #refreshPolicy: "CreatedOnce"
  target:
    name: apc-kafka-admin-with-username
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "apc-kafka-admin"
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: apc-kafka-admin
      property: password
