apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ck-kafka-kafka-backup
  namespace: ck-kafka
spec:
  bucketName: ck-kafka-kafka-backup-bucket
  # generateBucketName:
  objectBucketName: ck-kafka-kafka-backup
  storageClassName: ocs-storagecluster-ceph-rgw
