apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: local-k8s-store
  namespace: ck-kafka
spec:
  provider:
    kubernetes:
      # This points the store to the local cluster API
      remoteNamespace: ck-kafka
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        # Uses the ServiceAccount of the External Secrets Operator
        serviceAccount:
          name: eso-reader-sa
          # namespace: ck-kafka
          # namespace: apc-external-secrets-operator
          # name: deployer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-reader-sa
  namespace: ck-kafka
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader-role
  namespace: ck-kafka
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames:
    - apc-kafka-admin
    # - apc-kafka-admin-with-username
    # - 
  # You only need 'get' to fetch a specific secret
  verbs: ["get", "list", "watch"]
  # verbs: ["get", "list", "watch", "create", "update", "patch"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-reader-binding
  namespace: ck-kafka
subjects:
- kind: ServiceAccount
  name: eso-reader-sa
roleRef:
  kind: Role
  name: secret-reader-role
  apiGroup: rbac.authorization.k8s.io
