apiVersion: v1
kind: ConfigMap
metadata:
  name: apc-metallbips-range
  namespace: metallb-system
data:
  address-ranges: |
    {
      "range":
        {
          "start": "10.0.0.1",
          "end": "10.0.0.254",
        }
    }
