{{- if .Values.oauth.identityProviders }}
{{- range .Values.oauth.identityProviders }}
{{- $idpSecret := "" -}}
{{- $secretkey := "" -}}
{{- $secretCert := "" -}}
{{- $idpName := .name -}}
{{- if eq .type "LDAP"  }}
{{- $idpSecret = .ldap.bindPassword.name -}}
{{- $secretkey = "bindPassword" -}}
{{- else if eq .type "HTPasswd"  }}
{{- $idpSecret = .htpasswd.fileData.name -}}
{{- $secretkey = "fileData" -}}
{{- else if eq .type "Keystone"  }}
{{- $idpSecret = .keystone.tlsClientCert.name -}}
{{- $secretkey = "tlsClientKey" -}}
{{- $secretCert = "tlsClientCert" -}}
{{- else if eq .type "BasicAuth"  }}
{{- $idpSecret = .basicAuth.clientSecret.name -}}
{{- $secretkey = "clientSecret" -}}
{{- else if eq .type "GitHub"  }}
{{- $idpSecret = .github.clientSecret.name -}}
{{- $secretkey = "clientSecret" -}}
{{- else if eq .type "GitLab"  }}
{{- $idpSecret = .gitlab.clientSecret.name -}}
{{- $secretkey = "clientSecret" -}}
{{- else if eq .type "Google"  }}
{{- $idpSecret = .google.clientSecret.name -}}
{{- $secretkey = "clientSecret" -}}
{{- else if eq .type "OpenID"  }}
{{- $idpSecret = .openID.clientSecret.name -}}
{{- $secretkey = "clientSecret" -}}
{{- else }}
{{- $idpSecret := "" -}}
{{- $secretkey := "" -}}
{{- $secretCert := "" -}}
{{- end}}
{{- if ne $secretkey "" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $idpSecret }}
  namespace: {{ $.Release.Namespace }}
  labels:
  {{- ( include "cluster-config-standalone.labels" $ ) | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" $ }}
    kind: clusterSecretStore
  refreshInterval: "15m"
  target:
    name: {{ $idpSecret }}
    creationPolicy: Orphan
    deletionPolicy: Retain
    data:
    - secretKey: {{ $secretkey }}
      remoteRef:
        key: {{ $.Values.vaultKVmountPlatform }}/{{ include "apc-global-overrides.environmentShort" $ }}/openshift-config/oauth/identityProvider/{{ $idpSecret }}
        property: {{ $secretkey }}
{{- if ne $secretCert "" }}
    - secretKey: {{ $secretCert }}
      remoteRef:
        key: {{ $.Values.vaultKVmountPlatform }}/{{ include "apc-global-overrides.environmentShort" $ }}/openshift-config/oauth/identityProvider/{{ $idpSecret }}
        property: {{ $secretCert }}
{{- end}}
{{- end}}
---
{{- end}}
{{- end}}