# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

global:
  apc:
    customer: customer-global
    repoURL: repoURL-global
    repoTargetRevision: repoTargetRevision-global 
    environment: environment-global
    environmentShort: environmentShort-global
    cluster:
      name: clusterName-global
      acmName: clusterAcmName-global
      type: clusterType-global
      baseDomain: clusterBaseDomain-global
      appsDomain: clusterAppsDomain-global
      apiURL: clusterApiURL-global
      kubeVersion: clusterKubeVersion-global
      apiVersions:
        - clusterApiVersions-global
      services:
        global:
          url: clusterServicesGlobalUrl-global
        override:
          url: clusterServicesOverrideUrl-global
      isHub: true
      runsApps: true
    proxy: proxy-global
    noProxy: noProxy-global
    proxyCIDRs:
      - proxyIP-global
    services:
      global:
        url: servicesGlobalUrl-global
      certManager:
        defaultClusterIssuer: certManagerDefaultClusterIssuer-global
      crossplane:
        kubeVaultProviderConfigName: crossplaneKubeVaultProviderConfigName-global
        kubeKeycloakProviderConfigName: crossplaneKubeKeycloakProviderConfigName-global
      externalSecretsOperator:
        defaultClusterSecretStore: ESODefaultClusterSecretStore-global
      keycloak:
        url: keycloakUrl-global
        realm: keycloakName-global
      metallb:
        namespace: metallbNamespace-global
      quay:
        host: quayHost-global
      vault:
        kubeAuthMountPath: vaultKubeAuthMountPath-global
        name: vaultName-global
        url: vaultUrl-global
        KVmountPlatform: vaultKVmountPlatform-global
    caCertificates:
      override.crt: |
        -----BEGIN CERTIFICATE-----
        global
        -----END CERTIFICATE-----
      global.crt: |
        -----BEGIN CERTIFICATE-----
        global
        -----END CERTIFICATE-----
