# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

customer: customer-local
repoURL: repoURL-local
repoTargetRevision: repoTargetRevision-local 
environment: environment-local
environmentShort: environmentShort-local
cluster:
  name: clusterName-local
  acmName: clusterAcmName-local
  type: clusterType-local
  baseDomain: clusterBaseDomain-local
  appsDomain: clusterAppsDomain-local
  apiURL: clusterApiURL-local
  kubeVersion: clusterKubeVersion-local
  apiVersions:
    - clusterApiVersions-local
  services:
    local:
      url: clusterServicesLocalUrl-local
    override:
      url: clusterServicesOverrideUrl-local
  isHub: false
  runsApps: false
proxy: proxy-local
noProxy: noProxy-local
proxyCIDRs:
  - proxyIP-local1
  - proxyIP-local2
services:
  local:
    url: servicesLocaltUrl-local
  certManager:
    defaultClusterIssuer: certManagerDefaultClusterIssuer-local
  crossplane:
    kubeVaultProviderConfigName: crossplaneKubeVaultProviderConfigName-local
    kubeKeycloakProviderConfigName: crossplaneKubeKeycloakProviderConfigName-local
  externalSecretsOperator:
    defaultClusterSecretStore: ESODefaultClusterSecretStore-local
  keycloak:
    url: keycloakUrl-local
    realm: keycloakName-local
  metallb:
    namespace: metallbNamespace-local
  quay:
    host: quayHost-local
  vault:
    kubeAuthMountPath: vaultKubeAuthMountPath-local
    name: vaultName-local
    url: vaultUrl-local
    KVmountPlatform: vaultKVmountPlatform-local
caCertificates:
  override.crt: |
    -----BEGIN CERTIFICATE-----
    local
    -----END CERTIFICATE-----
  local.crt: |
    -----BEGIN CERTIFICATE-----
    local
    -----END CERTIFICATE-----
