apiVersion: v2
name: application-gitops
description: A Helm chart to prepare cluster for Application Gitops
type: application
version: 1.5.0
dependencies:
  - name: apc-global-overrides
    version: 1.5.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
