# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: {{ include "apps-ck-kafka.fullname" . }}-openshift-oauth-client-secret
#   namespace: {{ .Release.Namespace }}
#   labels:
#     {{- include "apps-ck-kafka.labels" . | nindent 4 }}
# spec:

#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: {{ include "apc-global-overrides.ESODefaultClusterSecretStore" . }}

#   # refreshInterval: "1h0m0s"
#   target:
#     name: {{ include "apps-ck-kafka.fullname" . }}-openshift-oauth-client-secret
#     creationPolicy: Owner
#     # creationPolicy: Orphan
#     deletionPolicy: Retain

#   # keys used are client-id, and client-secret
#   dataFrom:
#     - extract:
#         key: {{ include "apc-global-overrides.vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.environmentShort" . }}/{{ .Release.Namespace }}/oauth-credentials
