{{- if .Values.oauthProxy.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "apps-ck-kafka.fullname" . }}-oauth-proxy-cookie-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apps-ck-kafka.labels" . | nindent 4 }}
spec:
  refreshInterval: "0"
  #refreshPolicy it is not supported for external-secrets v 0.11
  #refreshPolicy: "CreatedOnce"
  target:
    name: {{ include "apps-ck-kafka.fullname" . }}-oauth-proxy-cookie-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "apps-ck-kafka.labels" . | nindent 10 }}
      data:
        secret: "{{ `{{ .password }}` }}" 
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: {{ include "apps-ck-kafka.fullname" . }}-oauth-proxy-cookie-secret
{{- end }}
