{{- if .Values.kafkaTopics.enabled }}
{{- range $topic := .Values.kafkaTopics.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $topic.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    strimzi.io/cluster: {{ include "apps-ck-kafka.fullname" $ }}
    {{- include "apps-ck-kafka.labels" $ | nindent 4 }}
spec:
  partitions: {{ $topic.partitions | default 3 }}
  replicas: {{ $topic.replicas | default 3 }}
  {{- if $topic.config }}
  config:
    {{- range $key, $value := $topic.config }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
