{{- if .Values.oauthProxy.enabled }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ include "apps-ck-kafka.fullname" . }}-oauth-proxy-cookie-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apps-ck-kafka.labels" . | nindent 4 }}
spec:
  length: 20
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: false
{{- end }}
