{{- if .Values.oauthProxy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "apps-ck-kafka.fullname" . }}-oauth-service-account-access
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apps-ck-kafka.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kafka.strimzi.io
  resources:
  - kafka
  verbs:
  - get
  resourceNames:
  - {{ include "apps-ck-kafka.fullname" . }}
{{- end }}
