# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
##   name: ck-kafka-kafka-ui
#   name: {{ include "apps-ck-kafka.fullname" . }}-kafka-ui
#   namespace: {{ .Release.Namespace }}
#   labels:
#     {{- include "apps-ck-kafka.labels" . | nindent 4 }}
# spec:
#   host: ck-kafka-kafka-ui-ck-kafka.apps.dev01.cloud.socpoist.sk
#   port:
#     targetPort: http
#   tls:
#     termination: edge
#   to:
#     kind: Service
#     name: ck-kafka-kafka-ui
#     weight: 100
#   wildcardPolicy: None
