{{- if .Values.oauthProxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apps-ck-kafka.fullname" . }}-oauth-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apps-ck-kafka.labels" . | nindent 4 }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ include "apps-ck-kafka.fullname" . }}-kafka-ui"}}'
{{- end }}
