{{- if .Values.oauthProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apps-ck-kafka.fullname" . }}-oauth-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apps-ck-kafka.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: {{ include "apps-ck-kafka.fullname" . }}-oauth-proxy
  type: ClusterIP
{{- end }}
