apiVersion: v2
name: apps-centralne-komponenty-bamoe
description: A Helm chart to configure Keycloak for Bamoe of "Centralne Komponenty"
type: application
version: 1.0.0
dependencies:
  - name: apc-global-overrides
    version: 1.6.0
    repository: file://../apc-global-overrides/
    # repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
