nameOverride: ""
fullnameOverride: ""

realmId: apps # toto by malo ist z globalnych values !!!!!!!!!!!!!!!!!!!!!!!!!!!
providerConfigRef: keycloak-local-config # toto by malo ist z globalnych values !!!!!!!!!!!!!!!!!!!!!!!!!!!

clientId: bamoe-management-console
clientName: bamoe

rootUrl: ~
baseUrl: ~
validRedirectUris: []
webOrigins: []
