nameOverride: ""
fullnameOverride: ""

clientId: bamoe-management-console
clientName: bamoe

rootUrl: ~
baseUrl: ~
validRedirectUris: []
webOrigins: []

## uses following global values => do not set here
# global:
#   apc:
#     services:
#       crossplane:
#         kubeKeycloakProviderConfigName: ~
#       keycloak:
#         realm: ~
## and their local overrides
# environmentShort: ~
# services:
#   crossplane:
#     kubeKeycloakProviderConfigName: ~
#       keycloak:
#         realm: ~
