apiVersion: v2
name: group-sync-operator
description: A Helm chart to install Group Sync Operator using ACM operator policy
type: application
version: 1.0.1
appVersion: 0.0.32

dependencies:
  - name: acm-operatorpolicy
    version: 1.2.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
