acm-operatorpolicy:
  subscription:
    channel: alpha
    name: group-sync-operator
    forceReleaseNamespace: true
    source: community-operators
    sourceNamespace: openshift-marketplace
    startingCSV: group-sync-operator.v0.0.32

  upgradeApproval: Automatic
  versions:
    - group-sync-operator.v0.0.32

  operatorGroup: 
    name: group-sync-operator
    namespace: group-sync-operator
    targetNamespaces:
      - group-sync-operator
