caBundle:
  name: ca-cert-bundle
  useDefaultCAs: true
  jksPassword: changeit
  namespaceTypes:
    - application
    - platform

imageRegistryS3Bundle:
  name: image-registry-s3-bundle
  useDefaultCAs: false
  namespace: openshift-config
