apiVersion: v2
name: user-workload-monitoring-policy
description: A Helm chart that automatically creates PrometheusRules for app / non-app workload namespaces
type: application
version: 1.0.7

dependencies:
  - name: apc-global-overrides
    version: 1.5.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
  - name: monitoring-prometheusrules
    version: 1.0.10
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/SPEXAPC-8954
