apiVersion: v2
name: etcd-hcp-backup
description: A Helm chart for Openshift Hosted Control Plane etcd backup
type: application
version: 1.1.0
dependencies:
  - name: apc-global-overrides
    version: 1.4.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
