apiVersion: v2
name: compliance-operator
description: A Helm chart to install OpenShift Compliance Operator
type: application
version: 1.0.1
appVersion: "stable"

dependencies:
  - name: acm-operatorpolicy
    version: "1.3.0"
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
