apiVersion: v2
name: apps-centralne-komponenty
description: A Helm chart to deploy "Centrálny Komponent Integračné Služby" integration
type: application
version: 1.0.0
# appVersion: "1.16.0"
dependencies:
  - name: apc-global-overrides
    version: 1.5.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
