{{- if eq (include "apc-global-overrides.clusterIsHub" .) "true" }}
---
apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: {{ .Values.central.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acs-config.labels" . | nindent 4 }}
spec:
  {{- .Values.central.spec | toYaml | nindent 2 }}
{{- end }}
