{{- if or .Values.prometheusRule.enabled (eq (include "apc-global-overrides.clusterIsHub" .) "true") }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Values.prometheusRule.name }}
  namespace: {{ .Values.prometheusRule.namespace | default .Values.stackrox.namespace }}
  labels:
    {{- include "acs-config.labels" . | nindent 4 }}
    {{- with .Values.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    {{- range $path, $_ := .Files.Glob "prometheus-rules/*.yaml" }}
    {{- $.Files.Get $path | nindent 4 }}
    {{- end }}
{{- end }}
