apiVersion: v2
name: apc-warmcache
description: A Helm chart for warming registry cache by syncing images using skopeo
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: apc-global-overrides
    version: 1.5.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/