apiVersion: v2
name: etcd-backup
description: A Helm chart for Standalone Openshift etcd backup configurations
version: 1.0.0
dependencies:
- name: apc-global-overrides
  version: 1.5.0
  repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
