apiVersion: v2
name: openshift-etcd-backup
description: A Helm chart for Openshift etcd backup configurations
version: 1.2.0
dependencies:
  - name: apc-global-overrides
    version: 1.4.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
