apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Release.Name }}
  namespace: {{ include "apc-global-overrides.metallbNamespace" . }}
  labels:
    {{- include "mongodb-config.labels" . | nindent 4 }}
spec:
  interfaces:
  - {{ .Values.l2Interface}}
  ipAddressPools:
  - {{ printf "%s-mongodb" .Release.Namespace }}
