apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-database-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb-config.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-database-agent
subjects:
  - kind: ServiceAccount
    name: {{ .Values.saName }}