apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-svcmon" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ printf "%s-svc" .Release.Name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: prometheus
    interval: 30s
    scrapeTimeout: 25s
    basicAuth:
      username:
        name: metrics-endpoint-password
        key: username
      password:
        name: metrics-endpoint-password
        key: password