---
apiVersion: v1
kind: Service
metadata:
  name: {{ (index .Values "mongodb-kubernetes").operator.name }}-monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ (index .Values "mongodb-kubernetes").operator.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ (index .Values "mongodb-kubernetes").operator.name }}
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ (index .Values "mongodb-kubernetes").operator.name }}-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ (index .Values "mongodb-kubernetes").operator.name }}
spec:
  selector:
    matchLabels:
      name: {{ (index .Values "mongodb-kubernetes").operator.name }}
  endpoints:
    - interval: 30s
      port: metrics
      scheme: http
      path: /metrics
