# IPAddressPool - reserved
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: test-kafka
  namespace: metallb-system
spec:
  addresses:
  - 10.14.76.43/32
  - 10.14.76.44/32
  - 10.14.76.45/32
  - 10.14.76.46/32
  autoAssign: true
  serviceAllocation:
    namespaces:
    - test
