apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: my-cluster-backup
spec:
  # generateBucketName: my-cluster-backup
  bucketName: my-cluster-backup-123
  storageClassName: ocs-storagecluster-ceph-rgw
