apiVersion: v2
name: monitoring
description: A Helm chart for cluster monitoring with Kyverno PrometheusRule generation
type: application
version: 1.0.6

dependencies:
  - name: apc-global-overrides
    version: 1.5.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
  - name: monitoring-prometheusrules
    version: 1.0.4
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
    # repository: 'file://../monitoring-prometheusrules'
