apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-init-rb
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "vault-helm.labels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
roleRef:
  kind: Role
  name: vault-init-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-snapshot-rb
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "vault-helm.labels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
roleRef:
  kind: Role
  name: vault-snapshot-role
  apiGroup: rbac.authorization.k8s.io
