acm-operatorpolicy:
  subscription:
    channel: stable
    name: rhacs-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: rhacs-operator.v4.8.7

  upgradeApproval: Automatic
  versions:
    - rhacs-operator.v4.8.7
