apiVersion: v2
name: grafana-apc-instance
description: A Helm chart for installing APC Grafana Instance
type: application
version: 1.0.1
appVersion: "v5"
kubeVersion: '>=1.16-0'

dependencies:
  - name: apc-global-overrides
    version: 1.5.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
