apiVersion: v2
name: kafka-backup-operator
description: A Helm chart to install OSO Kafka Backup Operator
type: application
version: 0.1.0
appVersion: "0.2.6"
dependencies:
  - name: kafka-backup-operator
    version: 0.2.6
    repository: https://osodevops.github.io/helm-charts/
