apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    # class: premium-rwo-retain
    volumes:
      - id: 0
        type: persistent-claim
        # class: premium-rwo-retain
        size: 10Gi
        kraftMetadata: shared
        deleteClaim: false
  template:
    pod:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: strimzi.io/pool-name
                    operator: In
                    values:
                    - controller
              topologyKey: "kubernetes.io/hostname"
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    # class: premium-rwo-retain
    volumes:
      - id: 0
        type: persistent-claim
        # class: premium-rwo-retain
        size: 99Gi
        kraftMetadata: shared
        deleteClaim: false
  template:
    pod:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: strimzi.io/pool-name
                    operator: In
                    values:
                    - broker
              topologyKey: "kubernetes.io/hostname"
---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: route
        tls: true
        authentication:
          type: scram-sha-512
      - name: externallb
        port: 9095
        type: loadbalancer
        tls: true
        authentication:
          type: scram-sha-512
      - name: externalnp
        port: 9096
        type: nodeport
        tls: true
        authentication:
          type: scram-sha-512
    # authorization:
    #   type: simple
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: "1"
    jvmOptions:
      -Xms: 750m
      -Xmx: 750m # Set Xms and Xmx same to prevent heap resizing jitter
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      # metric.reporters: "com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter"
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    rack:
      topologyKey: topology.kubernetes.io/zone
  # clientsCa:
  # clusterCa:
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
  entityOperator:
    topicOperator: {}
    userOperator: {}
#   cruiseControl:
# #    image: 123456789654.dkr.ecr.ap-south-1.amazonaws.com/cruise-control-ui:latest
#     config:
#       webserver.security.enable: false
#     metricsConfig:
#       type: jmxPrometheusExporter
#       valueFrom:
#         configMapKeyRef:
#           name: cruise-control-metrics
#           key: metrics-config.yml
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: my-user-pass
    type: scram-sha-512
  # authorization:
  #   type: simple
  #   acls:
  #     # Example ACL rules for consuming from my-topic using consumer group my-group
  #     - resource:
  #         type: topic
  #         name: my-topic
  #         patternType: literal
  #       operations:
  #         - Describe
  #         - Read
  #       host: "*"
  #     - resource:
  #         type: group
  #         name: my-group
  #         patternType: literal
  #       operations:
  #         - Read
  #       host: "*"
  #     # Example ACL rules for producing to topic my-topic
  #     - resource:
  #         type: topic
  #         name: my-topic
  #         patternType: literal
  #       operations:
  #         - Create
  #         - Describe
  #         - Write
  #       host: "*"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-user-tls
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  # authorization:
  #   type: simple
  #   acls:
  #     # Example ACL rules for consuming from my-topic using consumer group my-group
  #     - resource:
  #         type: topic
  #         name: my-topic
  #         patternType: literal
  #       operations:
  #         - Describe
  #         - Read
  #       host: "*"
  #     - resource:
  #         type: group
  #         name: my-group
  #         patternType: literal
  #       operations:
  #         - Read
  #       host: "*"
  #     # Example ACL rules for producing to topic my-topic
  #     - resource:
  #         type: topic
  #         name: my-topic
  #         patternType: literal
  #       operations:
  #         - Create
  #         - Describe
  #         - Write
  #       host: "*"
