resources:
  - ipaddresspool.yaml
  - l2advertisement.yaml
  - obc.yaml
  - kafka-metrics-cm.yaml
  - kafka-multinode.yaml
  - netpol.yaml
  - secret-push.yaml
  - kafka-connect-or.yaml

# - netpol.yaml
