# kubectl create secret docker-registry push-secret  --docker-server=apc-registry-quay-quay.apps.hub01.cloud.socpoist.sk   --docker-username=bbb   --docker-password=aaa -o yaml
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhcGMtcmVnaXN0cnktcXVheS1xdWF5LmFwcHMuaHViMDEuY2xvdWQuc29jcG9pc3Quc2siOnsidXNlcm5hbWUiOiJhcGMrYXNwX3JvYm90X2FwYyIsInBhc3N3b3JkIjoiUTlKMzRRTjNTWFZTQTQ0RlgxMUlQS1dUMVE0TVYxWk1RSDBDSTgxRFlQQjYxN1dUVjJYVDZIRENPOUgxTUdUNCIsImF1dGgiOiJZWEJqSzJGemNGOXliMkp2ZEY5aGNHTTZVVGxLTXpSUlRqTlRXRlpUUVRRMFJsZ3hNVWxRUzFkVU1WRTBUVll4V2sxUlNEQkRTVGd4UkZsUVFqWXhOMWRVVmpKWVZEWklSRU5QT1VneFRVZFVOQT09In19fQ==
kind: Secret
metadata:
  name: push-secret
type: kubernetes.io/dockerconfigjson
