apiVersion: v2
name: openshift-adp-config
description: A Helm chart to configure OpenShift ADP with DataProtectionApplication and Kyverno-based credential transformation
type: application
version: 1.0.1
appVersion: "v1.4.3"

dependencies:
  - name: apc-global-overrides
    version: "1.5.0"
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
