
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-prometheus-blackbox-exporter
  namespace: apc-blackbox-exporter
  labels:
    helm.sh/chart: prometheus-blackbox-exporter-11.6.1
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: blackbox-exporter
    app.kubernetes.io/version: "v0.28.0"
    app.kubernetes.io/managed-by: Helm
data:
  blackbox.yaml: |
    modules:
      http_2xx:
        http:
          follow_redirects: true
          method: GET
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          tls_config:
            insecure_skip_verify: true
          valid_http_versions:
          - HTTP/1.0
          - HTTP/1.1
          - HTTP/2
          - HTTP/2.0
        prober: http
        timeout: 30s
      http_openshift_api:
        http:
          fail_if_body_not_matches_regexp:
          - ^ok
          method: GET
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          tls_config:
            insecure_skip_verify: true
          valid_http_versions:
          - HTTP/2.0
          valid_status_codes:
          - 200
        prober: http
        timeout: 10s
      http_openshift_console:
        http:
          method: GET
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          tls_config:
            insecure_skip_verify: true
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2.0
          valid_status_codes:
          - 200
        prober: http
        timeout: 15s
      icmp:
        icmp:
          preferred_ip_protocol: ip4
        prober: icmp
        timeout: 5s
      tcp_probe:
        prober: tcp
        tcp:
          preferred_ip_protocol: ip4
        timeout: 10s
