apiVersion: v2
name: crossplane-keycloak-provider
description: A Helm chart to deploy Crossplane Keycloak provider
type: application
version: 1.0.0
appVersion: "v2.9.0"
dependencies:
  - name: apc-global-overrides
    version: 1.5.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
