nameOverride: ""
fullnameOverride: ""

providerPackage: xpkg.crossplane.io/crossplane-contrib/provider-keycloak:v2.9.0

replicas: 2

## uses following global values => do not set here
# global:
#   apc:
#     caCertificates: ~
## and their local overrides
# caCertificates: ~ # CAs to validate Vault cert. String of concatenated PEM encoded certs as opposed to the global value, which is a dictionary of strings. If not specified, defaults to global.apc.caCertificates.
