apiVersion: v2
name: cluster-config-standalone
description: A Helm chart to configure standalone cluster settings
type: application
version: 1.0.1
dependencies:
  - name: apc-global-overrides
    version: 1.4.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
