---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "etcd-hcp-backup.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs:     ["list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs:     ["get"]
  resourceNames:
  {{- range $idx := untilStep 0 5 1 }}
  - {{ default "etcd" $.Values.etcdStatefulSetName }}-{{ $idx }}
  {{- end }}
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs:     ["create"]
  resourceNames:
  {{- range $idx := untilStep 0 5 1 }}
  - {{ default "etcd" $.Values.etcdStatefulSetName }}-{{ $idx }}
  {{- end }}
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs:     ["get"]
  resourceNames: ["{{ default "etcd" .Values.etcdStatefulSetName }}"]
