---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "openshift-hcp-etcd-backup.name" . }}
  namespace: {{ include "openshift-hcp-etcd-backup.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "openshift-hcp-etcd-backup.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "openshift-hcp-etcd-backup.name" . }}
  apiGroup: rbac.authorization.k8s.io
