apiVersion: v2
name: group-sync-config
description: A Helm chart to setup Group Sync
type: application
version: 1.0.4
appVersion: "1.0.0"

dependencies:
  - name: apc-global-overrides
    version: "1.5.0"
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/