apiVersion: v2
name: kyverno
description: A Helm chart to install kyverno
type: application
version: 1.3.0
appVersion: "3.5.1"

dependencies:
  - name: kyverno
    version: 3.5.1
    repository: https://kyverno.github.io/kyverno
