
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: blackbox-exporter-egress-allow-proxy
  namespace: apc-blackbox-exporter
  labels:
    helm.sh/chart: blackbox-exporter-1.0.0
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/instance: blackbox-exporter
    app.kubernetes.io/version: "11.6.1"
    app.kubernetes.io/managed-by: Helm
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 1.1.1.7/32
  podSelector: {}
  policyTypes:
  - Egress