{{- if .Values.networkPolicy.allowProxyEgress }}
{{- if (include "apc-global-overrides.proxyCIDRs" . | fromYamlArray ) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "blackbox-exporter-helm.fullname" $ }}-allow-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blackbox-exporter-helm.labels" $ | nindent 4 }}
spec:
  egress:
  - to:
    {{- range (include "apc-global-overrides.proxyCIDRs" . | fromYamlArray ) }}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
  podSelector: {}
  policyTypes:
  - Egress
{{- end }}
{{- end }}
