nameOverride: ""
fullnameOverride: ""

functions:
  - name: auto-ready
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready:v0.5.2
  - name: go-templating
    package: xpkg.crossplane.io/crossplane-contrib/function-go-templating:v0.11.1
