apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: bpm
spec:
  deletionPolicy: Delete
  forProvider:
    realmId: apps
    clientId: bpm
    name: BPM
    description: BPM mikrosluzba
    accessType: BEARER-ONLY # CONFIDENTIAL, PUBLIC, BEARER-ONLY
    frontchannelLogoutEnabled: true
  providerConfigRef:
    name: keycloak-local-config
