apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mikroservice-admin
  # labels:
  #   rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
- apiGroups:
  - apc.cloud.socpoist.sk
  resources:
  - mikroservices
  verbs:
  - "*"
