apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: RoleMapper
metadata:
  name: bpm-admin-bpm-reader
spec:
  deletionPolicy: Delete
  forProvider:
    realmId: apps
    clientIdRef:
      name: bpm-admin
    roleIdRef:
      # must match the manifest name, which created the role!
      name: bpm-reader
  providerConfigRef:
    name: keycloak-local-config
---
apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: RoleMapper
metadata:
  name: bpm-admin-bpm-worker
spec:
  deletionPolicy: Delete
  forProvider:
    realmId: apps
    clientIdRef:
      name: bpm-admin
    roleIdRef:
      # must match the manifest name, which created the role!
      name: bpm-worker
  providerConfigRef:
    name: keycloak-local-config
---
apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: RoleMapper
metadata:
  name: bpm-admin-bpm-admin
spec:
  deletionPolicy: Delete
  forProvider:
    realmId: apps
    clientIdRef:
      name: bpm-admin
    roleIdRef:
      # must match the manifest name, which created the role!
      name: bpm-admin
  providerConfigRef:
    name: keycloak-local-config
---
