apiVersion: apc.cloud.socpoist.sk/v1alpha1
kind: mikroservice
metadata:
  name: example
  namespace: test
spec:
  # crossplane:
  #   compositionRef:
  #     name: example
  name: bpm
  # crossplane:
  #   compositionRef:
  #     name: example
