apiVersion: v2
name: compliance-config
description: Configuration resources (ScanSettings, bindings, TailoredProfiles) for the OpenShift Compliance Operator
type: application
version: 1.0.1
appVersion: "1.0"
dependencies:
  - name: apc-global-overrides
    version: "1.5.0"
    repository: "https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/"
