apiVersion: v2
name: kyverno-app-project
description: A Helm chart to create kyverno policies to set specific limits, quotas and proxy for projects.
type: application
version: 1.3.1
dependencies:
  - name: apc-global-overrides
    version: 1.5.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
