apiVersion: v2
name: mongodb-config
description: A Helm chart to deploy customized MongoDb instance
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: apc-global-overrides
    version: 1.5.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/