{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-%s" (include "apc-warmcache.fullname" .) .Values.rbac.clusterRoleBinding.name }}
  labels:
    {{- include "apc-warmcache.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-%s" (include "apc-warmcache.fullname" .) .Values.rbac.clusterRole.name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "apc-warmcache.serviceAccountName" . }}
    namespace: {{ include "apc-warmcache.namespace" . }}
{{- end }}
