{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.regca.name }}
  namespace: {{ include "apc-warmcache.namespace" . }}
  labels:
    {{- include "apc-warmcache.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  target:
    name: {{ .Values.externalSecrets.regca.targetSecretName }}
  data:
    - secretKey: regca.crt
      remoteRef:
        key: {{ .Values.externalSecrets.regca.vault.key }}
        property: {{ .Values.externalSecrets.regca.vault.property }}
{{- end }}
