apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.regca.name }}
  namespace: {{ include "apc-warmcache.namespace" . }}
  labels:
    {{- include "apc-warmcache.labels" . | nindent 4 }}
stringData:
  {{- include "apc-global-overrides.caCertificates" . | nindent 2 }}
type: Opaque
