# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: keycloak:aggregate-to-crossplane
#   labels:
#     rbac.crossplane.io/aggregate-to-crossplane: "true"
# rules:
# - apiGroups:
#   - openidclient.keycloak.m.crossplane.io
#   resources:
#   - clients
#   - clientserviceaccountrole
#   verbs:
#   - "*"
# - apiGroups:
#   - client.keycloak.m.crossplane.io
#   resources:
#   - rolemappers
#   - protocolmapper
#   verbs:
#   - "*"
# - apiGroups:
#   - group.keycloak.m.crossplane.io
#   resources:
#   - groups
#   - roles
#   verbs:
#   - "*"
# - apiGroups:
#   - role.keycloak.m.crossplane.io
#   resources:
#   - roles
#   verbs:
#   - "*"
